estimator:
  - name: categorical-encoder
    params:
      one_hot: false
      force_dense_array: true
      pass_through_columns:
  - name: crosser
    params: 
      columns: ["age", "bmi"]

  - name: gradient-boosting-regressor
    params: 
        learning_rate: 0.05
        max_depth: 2
        n_estimators: 145

data:
  filepath: ./train_regression.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: gradient-boosting-regressor
      params:
        learning_rate: [0.04,0.05,0.06]
        n_estimators: [120,125,130,135, 140, 145]
        max_depth: [1,2,3,4,5]

export:
  output_dir: ./models

reports:
  dir: ./reports