estimator:
  - name: categorical-encoder
    params:
      one_hot: false
      force_dense_array: true
      pass_through_columns:
  - name: crosser
    params: 
      columns: ["age", "bmi"]
  - name: standard-scaler
    params: {}
  - name: linear-regressor
    params: {}

data:
  filepath: ./train_regression.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: random-forest-regressor
      params:
        n_estimators: [100,110,130,150]
        max_depth: [3,4,5,7,9,12,15,20]
        min_samples_split: [2,4,6,8,10]

export:
  output_dir: ./models

reports:
  dir: ./reports