- name: categorical-encoder
  params:
    force_dense_array: true
    one_hot: false
    pass_through_columns: null
- name: standard-scaler
  params: {}
- name: stacking-regressor
  params:
    estimators:
    - ('lr'
    - RidgeCV())
    - ('svr'
    - LinearSVR(random_state=42))
